version: '3.9'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tips
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
  api:
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    environment:
      DB_PORT: 5432
      DB_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tips
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./nodeapp:/opt/api
    command: npm run dev
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:3000
    depends_on:
      - api
    environment:
      REACT_APP_LOCAL_BACKEND_URL: http://localhost:3000
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      WDS_SOCKET_PORT: 80
    volumes:
      - ./client:/opt/client
      - /opt/client/node_modules
    command: npm start

  db_init:
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    environment:
      DB_PORT: 5432
      DB_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tips
    depends_on:
      - db
    volumes:
      - ./nodeapp:/opt/api
    command: sh -c "sleep 10 && cd /opt/api && npm run seed:db"
