###
GET http://localhost:3000/getusers

###
GET http://localhost:3000/getall

###
POST http://localhost:3000/addtip
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "description": "Test tip description",
  "category": 6,
  "creator": "123456789"
} 

###
PATCH http://localhost:3000/1/update
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "description": "NEW TIP AGAIN",
  "category": 5
} 

### 
DELETE http://localhost:3000/9/delete
Authorization: BEARER {{authToken}}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "John Wayne",
  "email": "john@wayne.com",
  "password": "john@wayne"
}

###
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john@wayne.com",
  "password": "john@wayne"
}


###
@authToken = {{login.response.body.token}}