###
GET http://localhost:3000/getusers

###
GET http://localhost:3000/getall
###
GET http://localhost:3000/getall
###
PATCH http://localhost:3000/14/addALike
Authorization: BEARER {{authToken}}
###
POST http://localhost:3000/addtip
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "description": "Test tip description" ,
  "category": 2
} 

###
PATCH http://localhost:3000/13/update
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "description": "Edited tip",
  "category": 5
} 

### 
DELETE http://localhost:3000/9/delete
Authorization: BEARER {{authToken}}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "John Wayne",
  "email": "john@wayne.com",
  "password": "john@wayne"
}

###
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john@wayne.com",
  "password": "john@wayne"
}


###
@authToken = {{login.response.body.token}}